Update for Sprint 71
ManageIQ/manageiq-consumption pull request #114
Opened 2017-10-17 18:19 UTC by JPrause

[skip ci]

2017-10-17 18:19 UTC, JPrause commented
@miq-bot add_label documentation

2017-10-18 10:40 UTC, chargio requested changes
1. Initial version of manageiq-consumption
2. Functional parity with existing rate management in the old chargeback. It is possible to generate the same information using the old and the new chargeback.

2017-10-18 10:41 UTC, chargio commented on CHANGELOG.md
> +- Changes that correspond with "v5" commit of "chargio" branch in ManageIQ repo [(#95)](https://github.com/ManageIQ/manageiq-consumption/pull/95)
Changes that correspond with "v5" commit of "chargio" branch in ManageIQ repo [(#95)](https://github.com/ManageIQ/manageiq-consumption/pull/95). They allow the new chargeback to be plugged in subtituting the old rating

2017-10-18 13:08 UTC, chargio approved these changes

2017-10-18 13:08 UTC, merged