[WIP] Template feature
ManageIQ/manageiq-consumption pull request #46
Opened 2017-07-08 11:43 UTC by aljesusg

2017-07-10 07:10 UTC, chargio requested changes
Changes needed to make it easier to be understood. Name "template" is confliciting with a template for the feature

2017-07-10 07:10 UTC, sergio-ocon commented on app/models/manageiq/consumption/showback_event.rb
> +  include_concern 'TEMPLATE'
TEMPLATE should be changes to another name (perhaps VM_TEMPLATE). It is not clear defined as tempalte

Suggestions:
ENVELOPE
RESOURCES_REQUESTED
FLAVOR

2017-07-10 07:10 UTC, sergio-ocon commented on app/models/manageiq/consumption/showback_event.rb
> +        self.data[measure_type.measure][dim] = 0 unless measure_type.measure == "TEMPLATE"
This creates the necessity to test in every function that the template is different
[ [ value ] ]?
Normally only one would be needed.

2017-07-10 07:10 UTC, sergio-ocon commented on db/fixtures/showback_usage_types.yml
> +  :dimensions: ["number","memory_reserve"]
number? ===> cpu_reserved?

2017-07-10 07:10 UTC, sergio-ocon commented on spec/models/showback_event/mem_spec.rb
> +      expect(event.MEM_total_mem(4096)).to eq(4096)
Some comments are needed. I don't understasnt the test

2017-07-12 16:54 UTC, aljesusg commented on spec/models/showback_event/mem_spec.rb
> +      expect(event.MEM_total_mem(4096)).to eq(4096)
Thanks @sergio-ocon this is wrong, this calculate the max_memory used at month and not the actual :( I need change it

2017-07-13 08:06 UTC, sergio-ocon commented on app/models/manageiq/consumption/showback_column_units.yml
> +:total_mem: "Mb"
¿total mem unit?

2017-07-13 08:07 UTC, sergio-ocon commented on db/fixtures/showback_usage_types.yml
> +  :dimensions: ["number","memory_reserve"]
You can use any unit, if it is not identified we won't be able to translate it to K,M, etc

2017-07-13 08:22 UTC, chargio approved these changes
LGTM

2017-08-07 16:20 UTC, aljesusg commented on app/models/manageiq/consumption/showback_column_units.yml
> +:total_mem: "Mb"
I don't understand your question

2017-08-16 11:31 UTC, sergio-ocon commented on app/models/manageiq/consumption/showback_column_units.yml
> +:total_mem: "Mb"
My mistake

2017-09-01 08:35 UTC, closed without merging