[WIP]Features
ManageIQ/manageiq-consumption pull request #79
Opened 2017-08-28 21:00 UTC by aljesusg

- [X] Auto include all Libs in showback_event
- [X] Refactor measures calculation
- [ ] Add more measures
- [ ] Set correct units

2017-08-29 08:30 UTC, sergio-ocon commented on app/models/manageiq/consumption/showback_event.rb
> +  Dir.glob(Pathname.new(File.dirname(__dir__)).join("consumption/showback_event/*")).each { |lib| include_concern lib.split("consumption/showback_event/")[1].split(".rb")[0].upcase }
😄

2017-08-29 08:38 UTC, chargio requested changes
Some minor changes while you code it.

2017-08-29 08:38 UTC, sergio-ocon commented on app/models/manageiq/consumption/showback_event/common.rb
> +      resource.vim_performance_states.last.state_data[type.to_sym] || 0
Could you comment this code?
 It should be clear why we are doing this so it can be refactored in the future

2017-08-29 08:38 UTC, sergio-ocon commented on db/fixtures/showback_usage_types.yml
>    :dimensions: ["cpu_reserved","memory_reserve"]
memory_reserved?

2017-10-05 15:36 UTC, chessbyte commented
@aljesusg Please rebase and re-push

2017-10-09 16:51 UTC, closed without merging